# ==============================================================================
#  SITE IDENTITY & ENVIRONMENT
# ==============================================================================
title: Homelab Docs
tagline: Hi there, A docs site for my Homelab project.
description: >-
  A docs site for my Homelab Project.

# Change to your language and timezone
lang: en
timezone: Asia/Bangkok

# Theme Setting
theme: jekyll-theme-chirpy
theme_mode: # [light | dark]

# ==============================================================================
#  URL & DEPLOYMENT SETTINGS
# ==============================================================================
# ใส่ URL ของ GitHub Pages
# https://atlast01.github.io
url: "https://atlast01.github.io"

# Repo your Github pages is hosted on
baseurl: "/blog-post"

# ==============================================================================
#  AUTHOR & SOCIAL PROFILES
# ==============================================================================
social:
  name: At-last
  email: maitri90843@gmail.com
  links:
    - https://twitter.com/username
    - https://github.com/atlast01
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Social username shortcuts
github:
  username: atlast01
twitter:
  username: twitter_username

# Image URL for profile your  in sidebar
avatar: https://avatars.githubusercontent.com/u/121550703?v=4

# ==============================================================================
#  THEME FEATURES & EXTENSIONS
# ==============================================================================
# (Table of Contents)
toc: true

# Number of articles per page
paginate: 10

# Comment system (เลือกหนึ่งรายการเพื่อเปิดใช้งาน)
comments:
  provider: # [disqus | utterances | giscus]

# PWA system(ทำให้เว็บติดตั้งลงมือถือได้เหมือนแอป)
pwa:
  enabled: true
  cache:
    enabled: true

# Web Analytics (สถิติคนเข้าเว็บ)
analytics:
  google:
    id: # ใส่ Google Analytics ID # วิธีหา ID: https://analytics.google.com/
  goatcounter:
    id: # Guide: https://goatcounter.com/
  umami:
    id: # Guide: https://umami.is/

# ==============================================================================
#  BUILD & PROCESSING SETTINGS
#  Backend system settings (should not be modified unless necessary)
# ==============================================================================
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Option: https://github.com/jneen/rouge#full-options
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
  footnote_backlink: "&#8617;&#xfe0e;"

# Managing Collections (Website Tabs)
collections:
  tabs:
    output: true
    sort_by: order

# Default values ​​for different web page types.
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

# Compressing HTML for speed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Files that the system will not use to create a web page
exclude:
  - "*.gem"
  - "*.gemspec"
  - "*.config.js"
  - "package*.json"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js

# Plugin Settings
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

webmaster_verifications:
  google: # HTML Tag Verification Code จาก Google Search Console
    # วิธีหา: https://search.google.com/search-console (เลือกวิธี HTML Tag)
